version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/environments/dev"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "terraform"
    directory: "/environments/staging"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "terraform"
    directory: "/environments/prod"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
