name: Module Versioning

on:
  push:
    paths:
      - "modules/**"
    branches:
      - main

jobs:
  version_and_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed module
        id: changed_module
        run: |
          MODULE=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '^modules/' | cut -d/ -f2 | uniq)
          echo "module=$MODULE" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          RELEASE_BRANCHES: main
          VERBOSE: true
          TAG_CONTEXT: ${{ steps.changed_module.outputs.module }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            Changes in this Release
            - ${{ steps.changed_module.outputs.module }} updated to ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false
